=== djnugent/cdn/schemas/events.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Events",
  "description": "State fair event schedule",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "description": {
        "type": "string",
        "description": "The description of the event",
        "minLength": 10
      },
      "image": {
        "type": [
          "string",
          "null"
        ],
        "description": "The image url of the event",
        "format": "uri"
      },
      "slug": {
        "type": "string",
        "description": "The url slug of the event"
      },
      "id": {
        "type": "string",
        "description": "The unique identifier for the event",
        "format": "uuid"
      },
      "name": {
        "type": "string",
        "description": "The name of the event"
      },
      "venue_slug": {
        "type": "string",
        "description": "The venue slug of the event"
      },
      "schedule": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "start": {
              "type": "string",
              "description": "The start time of the event"
            },
            "end": {
              "type": [
                "string",
                "null"
              ],
              "description": "The end time of the event"
            }
          },
          "required": [
            "start",
            "end"
          ]
        }
      }
    },
    "required": [
      "description",
      "image",
      "slug",
      "id",
      "name",
      "venue_slug",
      "schedule"
    ]
  }
}

=== djnugent/cdn/events.json
[
    {
        "description": "Minnesota musician Alexander Craig captivates crowds with his high-energy fusion of rock \u2018n\u2019 roll, soul, punk and blues, inspiring dancers with a timeless rock beat. His newest music focuses on progression and perseverance, while touching on positive life philosophy and personal growth.",
        "image": "https://assets.mnstatefair.org/_core/img/database/entertainers/alexander-craig/featured.848x477.jpg?v=20240513.192215",
        "slug": "alexander-craig",
        "id": "f78d0df9-de5f-40df-e1f3-9b247ea9f381",
        "name": "Alexander Craig",
        "venue_slug": "schells-stage-at-schilling-amphitheater",
        "schedule": [
            {
                "start": "2024-08-24T16:00:00-05:00",
                "end": "2024-08-24T16:35:00-05:00"
            },
            {
                "start": "2024-08-24T17:00:00-05:00",
                "end": "2024-08-24T17:35:00-05:00"
            },
            {
                "start": "2024-08-24T18:00:00-05:00",
                "end": "2024-08-24T18:35:00-05:00"
            },
            {
                "start": "2024-08-25T16:00:00-05:00",
                "end": "2024-08-25T16:35:00-05:00"
            },
            {
                "start": "2024-08-25T17:00:00-05:00",
                "end": "2024-08-25T17:35:00-05:00"
            },
            {
                "start": "2024-08-25T18:00:00-05:00",
                "end": "2024-08-25T18:35:00-05:00"
            }
        ]
    },
    {
        "description": "America\u2019s favorite stunt dogs are returning to make a splash at the 2024 State Fair! From large to small breeds, these dogs will mesmerize you as they compete in challenges, dock dives and leaps into the air to catch flying discs, plus astounding stunts such as jumping rope, walking backwards and doing paw-stands. These canine stars are thrilling the nation \u2013 you may recognize them from \u201cThe Tonight Show,\u201d \u201cThe Ellen DeGeneres Show,\u201d \u201cThe Queen Latifah Show,\u201d Animal Planet, National Geographic, the Rose Parade and television commercials. All-Star Stunt Dogs Splash participated in the \u201cWorld Dog Awards\u201d hosted by George Lopez on the CW, where jump-rope dog \"Spitfire Spinelli\" was one of the top three trick dogs on the show! What makes these stunt dogs so special? Besides their talent for flipping, jumping and diving, these amazing pooches have been adopted from shelters across the country and turned into stars. Their mission is to promote pet adoption and spaying and neutering, while encouraging responsible pet ownership. The louder you cheer, the more air the dogs get and the bigger the splash! Come join the \u201cDog-Gone Fun\u201d happening daily.\n\nASL interpretation daily at 2 p.m.",
        "image": "https://assets.mnstatefair.org/_core/img/database/entertainers/all-star-stunt-dogs-splash/featured.848x477.jpg?v=20240429.155240",
        "slug": "all-star-stunt-dogs-splash",
        "id": "00751b8c-9e7a-81b6-5709-5d02389f27be",
        "name": "All-Star Stunt Dogs Splash",
        "venue_slug": "the-north-woods-stage",
        "schedule": [
            {
                "start": "2024-08-22T11:00:00-05:00",
                "end": "2024-08-22T11:30:00-05:00"
            },
            {
                "start": "2024-08-22T14:00:00-05:00",
                "end": "2024-08-22T14:30:00-05:00"
            },
            {
                "start": "2024-08-22T16:30:00-05:00",
                "end": "2024-08-22T17:00:00-05:00"
            },
            {
                "start": "2024-08-23T11:00:00-05:00",
                "end": "2024-08-23T11:30:00-05:00"
            },
            {
                "start": "2024-08-23T14:00:00-05:00",
                "end": "2024-08-23T14:30:00-05:00"
            },
            {
                "start": "2024-08-23T16:30:00-05:00",
                "end": "2024-08-23T17:00:00-05:00"
            },
            {
                "start": "2024-08-24T11:00:00-05:00",
                "end": "2024-08-24T11:30:00-05:00"
            },
            {
                "start": "2024-08-24T14:00:00-05:00",
                "end": "2024-08-24T14:30:00-05:00"
            },
            {
                "start": "2024-08-24T16:30:00-05:00",
                "end": "2024-08-24T17:00:00-05:00"
            },
            {
                "start": "2024-08-25T11:00:00-05:00",
                "end": "2024-08-25T11:30:00-05:00"
            },
            {
                "start": "2024-08-25T14:00:00-05:00",
                "end": "2024-08-25T14:30:00-05:00"
            },
            {
                "start": "2024-08-25T16:30:00-05:00",
                "end": "2024-08-25T17:00:00-05:00"
            },
            {
                "start": "2024-08-26T11:00:00-05:00",
                "end": "2024-08-26T11:30:00-05:00"
            },
            {
                "start": "2024-08-26T14:00:00-05:00",
                "end": "2024-08-26T14:30:00-05:00"
            },
            {
                "start": "2024-08-26T16:30:00-05:00",
                "end": "2024-08-26T17:00:00-05:00"
            },
            {
                "start": "2024-08-27T11:00:00-05:00",
                "end": "2024-08-27T11:30:00-05:00"
            },
            {
                "start": "2024-08-27T14:00:00-05:00",
                "end": "2024-08-27T14:30:00-05:00"
            },
            {
                "start": "2024-08-27T16:30:00-05:00",
                "end": "2024-08-27T17:00:00-05:00"
            },
            {
                "start": "2024-08-28T11:00:00-05:00",
                "end": "2024-08-28T11:30:00-05:00"
            },
            {
                "start": "2024-08-28T14:00:00-05:00",
                "end": "2024-08-28T14:30:00-05:00"
            },
            {
                "start": "2024-08-28T16:30:00-05:00",
                "end": "2024-08-28T17:00:00-05:00"
            },
            {
                "start": "2024-08-29T11:00:00-05:00",
                "end": "2024-08-29T11:30:00-05:00"
            },
            {
                "start": "2024-08-29T14:00:00-05:00",
                "end": "2024-08-29T14:30:00-05:00"
            },
            {
                "start": "2024-08-29T16:30:00-05:00",
                "end": "2024-08-29T17:00:00-05:00"
            },
            {
                "start": "2024-08-30T11:00:00-05:00",
                "end": "2024-08-30T11:30:00-05:00"
            },
            {
                "start": "2024-08-30T14:00:00-05:00",
                "end": "2024-08-30T14:30:00-05:00"
            },
            {
                "start": "2024-08-30T16:30:00-05:00",
                "end": "2024-08-30T17:00:00-05:00"
            },
            {
                "start": "2024-08-31T11:00:00-05:00",
                "end": "2024-08-31T11:30:00-05:00"
            },
            {
                "start": "2024-08-31T14:00:00-05:00",
                "end": "2024-08-31T14:30:00-05:00"
            },
            {
                "start": "2024-08-31T16:30:00-05:00",
                "end": "2024-08-31T17:00:00-05:00"
            },
            {
                "start": "2024-09-01T11:00:00-05:00",
                "end": "2024-09-01T11:30:00-05:00"
            },
            {
                "start": "2024-09-01T14:00:00-05:00",
                "end": "2024-09-01T14:30:00-05:00"
            },
            {
                "start": "2024-09-01T16:30:00-05:00",
                "end": "2024-09-01T17:00:00-05:00"
            },
            {
                "start": "2024-09-02T11:00:00-05:00",
                "end": "2024-09-02T11:30:00-05:00"
            },
            {
                "start": "2024-09-02T14:00:00-05:00",
                "end": "2024-09-02T14:30:00-05:00"
            },
            {
                "start": "2024-09-02T16:30:00-05:00",
                "end": "2024-09-02T17:00:00-05:00"
            }
        ]
    },
    {
        "description": "In the whimsical world of All\u00e9z-OOPS! with Rob Lok, creativity and comedy come together to make an unforgettable experience. Blending circus thrills, deft pacing and spontaneous comedy, this high-octane slapstick spectacle excites all audiences with absurd sight gags, visual silliness and boundless joy.\n\nASL interpretation during 3:30 p.m. show.",
        "image": "https://assets.mnstatefair.org/_core/img/database/entertainers/allez-oops/featured.848x477.jpg?v=20240426.191956",
        "slug": "allez-oops",
        "id": "d7308c02-b5f8-a83c-2aed-f391fcdebd07",
        "name": "All\u00e9z-OOPS! Circus. Comedy. Spectacle.",
        "venue_slug": "family-fair-stage",
        "schedule": [
            {
                "start": "2024-08-28T12:30:00-05:00",
                "end": "2024-08-28T13:00:00-05:00"
            },
            {
                "start": "2024-08-28T15:30:00-05:00",
                "end": "2024-08-28T16:00:00-05:00"
            },
            {
                "start": "2024-08-29T12:30:00-05:00",
                "end": "2024-08-29T13:00:00-05:00"
            },
            {
                "start": "2024-08-29T15:30:00-05:00",
                "end": "2024-08-29T16:00:00-05:00"
            },
            {
                "start": "2024-08-30T12:30:00-05:00",
                "end": "2024-08-30T13:00:00-05:00"
            },
            {
                "start": "2024-08-30T15:30:00-05:00",
                "end": "2024-08-30T16:00:00-05:00"
            },
            {
                "start": "2024-08-31T12:30:00-05:00",
                "end": "2024-08-31T13:00:00-05:00"
            },
            {
                "start": "2024-08-31T15:30:00-05:00",
                "end": "2024-08-31T16:00:00-05:00"
            },
            {
                "start": "2024-09-01T12:30:00-05:00",
                "end": "2024-09-01T13:00:00-05:00"
            },
            {
