=== djnugent/cdn/schemas/landmarks.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "title": "Landmarks",
    "description": "State fair landmarks",
    "type": "object",
    "properties": {
        "atms": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "Sub type of ATM",
                        "enum": [
                            "normal"
                        ]
                    },
                    "location": {
                        "type": "array",
                        "description": "Lat lon",
                        "items": {
                            "type": "number"
                        },
                        "minItems": 2,
                        "maxItems": 2
                    }
                },
                "required": [
                    "type",
                    "location"
                ]
            }
        },
        "restrooms": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "Sub type of restroom",
                        "enum": [
                            "normal",
                            "baby_change",
                            "accessible_baby_change",
                            "family_accessible"
                        ]
                    },
                    "location": {
                        "type": "array",
                        "description": "Lat lon",
                        "items": {
                            "type": "number"
                        },
                        "minItems": 2,
                        "maxItems": 2
                    }
                },
                "required": [
                    "type",
                    "location"
                ]
            }
        },
        "water": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "Sub type of water",
                        "enum": [
                            "normal"
                        ]
                    },
                    "location": {
                        "type": "array",
                        "description": "Lat lon",
                        "items": {
                            "type": "number"
                        },
                        "minItems": 2,
                        "maxItems": 2
                    }
                },
                "required": [
                    "type",
                    "location"
                ]
            }
        },
        "gates": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "Sub type of gate",
                        "enum": [
                            "normal"
                        ]
                    },
                    "location": {
                        "type": "array",
                        "description": "Lat lon",
                        "items": {
                            "type": "number"
                        },
                        "minItems": 2,
                        "maxItems": 2
                    }
                },
                "required": [
                    "type",
                    "location"
                ]
            }
        }
    },
    "required": [
        "atms",
        "restrooms",
        "water",
        "gates"
    ]
}

=== djnugent/cdn/landmarks.json
{
    "restrooms": [
        {
            "type": "normal",
            "location": [
                -93.17743637470019,
                44.97782488927484
            ]
        },
        {
            "type": "baby_change",
            "location": [
                -93.17633772261256,
                44.977811194736404
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.1749801561278,
                44.97783155013812
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.17701928739106,
                44.978715822563004
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17665579007885,
                44.978929049333715
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17491809561139,
                44.97891650660475
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.17378793940411,
                44.978386839327214
            ]
        },
        {
            "type": "family_accessible",
            "location": [
                -93.1735183238981,
                44.97959530673913
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17762516271968,
                44.98032156215106
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.1756332190123,
                44.980378942236456
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17921882143722,
                44.98036064838777
            ]
        },
        {
            "type": "family_accessible",
            "location": [
                -93.17794444076435,
                44.98112395534926
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.17383969733447,
                44.98106973871117
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.17249656212226,
                44.981149441152354
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.17099207125352,
                44.97835836547509
            ]
        },
        {
            "type": "baby_change",
            "location": [
                -93.17183639775502,
                44.9792672958412
            ]
        },
        {
            "type": "family_accessible",
            "location": [
                -93.1700110464106,
                44.9783346145538
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17012511352974,
                44.97922799474085
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.16896210426694,
                44.98032036938565
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.17005469939119,
                44.980528259222126
            ]
        },
        {
            "type": "family_accessible",
            "location": [
                -93.17112208559344,
                44.980574757351945
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.16772428136008,
                44.98080494453998
            ]
        },
        {
            "type": "family_accessible",
            "location": [
                -93.16952608324698,
                44.981791823998435
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.16747722980215,
                44.98179958367754
            ]
        },
        {
            "type": "accessible_baby_change",
            "location": [
                -93.1676302142119,
                44.98320452818734
            ]
        },
        {
            "type": "family_accessible",
            "location": [
                -93.16981802503659,
                44.98414825445337
            ]
        },
        {
            "type": "family_accessible",
            "location": [
                -93.16766365436608,
                44.98481815266814
            ]
        },
        {
            "type": "family_accessible",
            "location": [
                -93.16969083639137,
                44.98691165733456
            ]
        }
    ],
    "atms": [
        {
            "type": "normal",
            "location": [
                -93.16898043108185,
                44.978649259473855
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17032083905126,
                44.97869427496289
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17238222148258,
                44.97849253141976
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17443916794527,
                44.97850193987125
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.1755460197766,
                44.97845023468895
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17563417269763,
                44.97973262359122
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17545861431974,
                44.98041114735915
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17597951813812,
                44.98159605612912
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17523762092475,
                44.981253540473574
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17391749148703,
                44.98106423407387
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17238392160476,
                44.98117207777315
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17201927650402,
                44.981349161741065
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17415922929196,
                44.981808473179456
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17263774846005,
                44.98196602116147
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.1723006064485,
                44.97995160473886
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.1736821727997,
                44.979712047134285
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17516309648298,
                44.977930449498274
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.16898693447807,
                44.98029696331923
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17152590235065,
                44.97998437614146
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.1701136804814,
                44.981338450517825
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17038238672266,
                44.98316752470819
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17063864728333,
                44.98459367860784
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.16923159159683,
                44.98592565825933
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17032187659463,
                44.98731863036787
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.16889623276668,
                44.98405157676186
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.16782231855177,
                44.98096950090391
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.1704071144122,
                44.98039003121568
            ]
        }
    ],
    "water": [
        {
            "type": "normal",
            "location": [
                -93.17620876245685,
                44.98140993696251
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17635572603693,
                44.98066236964888
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17550121474422,
                44.98035328592488
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.17380836614045,
                44.98107362143617
            ]
        },
        {
            "type": "normal",
            "location": [
                -93.1724603667736,
                44.981149930841184
