=== djnugent/cdn/schemas/new_this_year.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "description": {
                "type": "string"
            },
            "image": {
                "type": "string",
                "format": "uri"
            },
            "slug": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "format": "uuid"
            },
            "name": {
                "type": "string"
            },
            "vendor_slug": {
                "type": "string"
            }
        },
        "required": [
            "description",
            "image",
            "slug",
            "id",
            "name",
            "vendor_slug"
        ]
    }
}

=== djnugent/cdn/new_this_year.json
[
    {
        "description": "Traditional hummus, harissa barbacoa, corn, queso fresco, chili dust, shatta (hot sauce), crema, cilantro and pita puffs.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/al-taco-baba/landing.720x600.jpg",
        "slug": "al-taco-baba",
        "id": "a6224f91-1812-2289-3e8b-67e9823ccca6",
        "name": "Al Taco Baba",
        "vendor_slug": "5146.1"
    },
    {
        "description": "A buttery, crisp and caramelized pastry \u2013 a combination of a bagel and croissant: Everything Cream Cheese Ba-Sant is rolled in poppy seeds, sesame seeds, onion flakes, garlic flakes, black pepper and sea salt with a scallion cream cheese filling; Sweet Corn Ba-Sant is filled with fresh sweet corn custard and garnished with crunchy caramel corn.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/ba-sants-in-two-varieties/detail.720x600.jpg",
        "slug": "ba-sants-in-two-varieties",
        "id": "da0406cd-01ee-3d0e-2675-d059b1a8c495",
        "name": "Ba-Sants in Two Varieties \u2013 Everything Cream Cheese and Sweet Corn",
        "vendor_slug": "2336.1"
    },
    {
        "description": "Griddled bacon-wrapped Kramarczuk hot dog served on a Nordic Waffle with cheddar cheese, pickle slices and crispy onions and drizzled with burger sauce.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/bacon-wrapped-waffle-dog/landing.720x600.jpg",
        "slug": "bacon-wrapped-waffle-dog",
        "id": "8642be11-23fb-5e64-b27c-70ec5382d7a6",
        "name": "Bacon-Wrapped Waffle Dog",
        "vendor_slug": "1476.1"
    },
    {
        "description": "Holy Land hummus blended with fresh basil and topped with a mix of crushed walnuts, crushed red chili pepper, garlic and olive oil. Served with homemade garlic parmesan chips. (Hummus is vegan and gluten-free; chips are vegetarian-friendly with gluten-free option available.)",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/basil-hummus-with-spicy-walnut-topping/landing.720x600.jpg",
        "slug": "basil-hummus-with-spicy-walnut-topping",
        "id": "9f36f033-c362-1f75-c30d-8460805d8cdc",
        "name": "Basil Hummus With Spicy Walnut Topping",
        "vendor_slug": "3689.1"
    },
    {
        "description": "Bridgeman\u2019s vanilla ice cream topped with hot honey, spicy peanuts, whipped cream and a cherry. (Vegetarian, gluten-friendly)",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/bee-sting-sundae/landing.720x600.jpg",
        "slug": "bee-sting-sundae",
        "id": "f7784c80-20ab-ae93-73da-ce384113f421",
        "name": "Bee Sting Sundae",
        "vendor_slug": "1996.1"
    },
    {
        "description": "Birthday cake-flavored mini donuts coated with vanilla sugar, drizzled with icing, and dusted with sugar crystals and sprinkles.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/birthday-cake-mini-donuts/landing.720x600.jpg",
        "slug": "birthday-cake-mini-donuts",
        "id": "d65ff8bf-5b5e-859d-d980-6526b21ffd6e",
        "name": "Birthday Cake Mini Donuts",
        "vendor_slug": "5052.1"
    },
    {
        "description": "Scratch-made jumbo pizza dough pretzel, hand-twisted and stuffed with Ellsworth cheese curds, pepperoni and a Green Mill blend of Italian spices. Brushed with garlic butter and topped with diced pepperoni, herbs and parmesan cheese. Served with Green Mill pizza sauce.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/cheese-curd-stuffed-pizza-pretzel/landing.720x600.jpg",
        "slug": "cheese-curd-stuffed-pizza-pretzel",
        "id": "bb37ee4d-027d-e013-28be-a3c2f2c7a5a8",
        "name": "Cheese Curd Stuffed Pizza Pretzel",
        "vendor_slug": "2437.1"
    },
    {
        "description": "Eli\u2019s Cheesecake pieces covered in funnel cake batter, fried and dusted with powdered sugar and salt. Served with strawberry dipping sauce.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/cheesecake-curds/landing.720x600.jpg",
        "slug": "cheesecake-curds",
        "id": "b009e7bb-04f3-1c07-cd5e-d6f58b138909",
        "name": "Cheesecake Curds",
        "vendor_slug": "1416.1"
    },
    {
        "description": "Blend of ground chicken, cabbage, onion, ginger and other spices steamed in a dough wrapper. Served with tomato chutney. (Available Aug. 24-29 only) (New Vendor)",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/chicken-momo-with-tomato-chutney/landing.720x600.jpg",
        "slug": "chicken-momo-with-tomato-chutney",
        "id": "3636c818-dd0c-c711-7e78-af9863d32cb1",
        "name": "Chicken Momo With Tomato Chutney",
        "vendor_slug": "2764.1"
    },
    {
        "description": "Three choices of lemonade served with a cotton candy cloud spun onto the drinking straw: Summer Strawberry \u2013 strawberry lemonade topped with strawberry fields cotton candy; Happy Huckleberry \u2013 huckleberry lemonade topped with blackberry jam cotton candy; and Flower Power \u2013 violet lemonade topped with lavender love cotton candy.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/cloud-coolers-in-three-flavors/landing.720x600.jpg",
        "slug": "cloud-coolers-in-three-flavors",
        "id": "453bf62d-82e3-0719-b039-d09ab618703b",
        "name": "Cloud Coolers in Three Flavors",
        "vendor_slug": "5175.1"
    },
    {
        "description": "Steamed lotus bun filled with a blend of cabbage, carrots, cilantro and yum yum sauce, plus Olsen Fish Company lutefisk brined in salt water for 12 hours, covered in sweet hoisin sauce, then baked and topped with sesame seeds.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/crispy-lutefisk-steam-bun/landing.720x600.jpg",
        "slug": "crispy-lutefisk-steam-bun",
        "id": "ab6c5ff7-b338-52b1-9271-172ab441a989",
        "name": "Crispy Lutefisk Steam Bun",
        "vendor_slug": "3276.1"
    },
    {
        "description": "Deep-fried tortilla filled with vegan roast beef, bacon and cheese sauce, plus peppers, onions and a hashbrown patty. Served with vegan Follow Your Heart seasoned sour cream. (Vegan)",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/crunchy-balboa/landing.720x600.jpg",
        "slug": "crunchy-balboa",
        "id": "26c80a49-11b0-78a4-f6de-ca66a2c2db3b",
        "name": "Crunchy Balboa",
        "vendor_slug": "5836.1"
    },
    {
        "description": "Fried white cheddar cheese curds, sandwich stacker dill pickles, cream cheese, lettuce and raspberry chipotle sauce in a fried flour tortilla. (Vegetarian)",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/dill-pickle-cheese-curd-taco/landing.720x600.jpg",
        "slug": "dill-pickle-cheese-curd-taco",
        "id": "d7f83816-565c-ecd4-d27e-d16dc7b7762d",
        "name": "Dill Pickle Cheese Curd Taco",
        "vendor_slug": "5275.1"
    },
    {
        "description": "Mini donuts wrapped in bacon, on-a-stick, then deep-fried, topped with a layer of peanut butter and drizzled with raspberry dessert sauce.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/donut-delights/landing.720x600.jpg",
        "slug": "donut-delights",
        "id": "11467df2-0255-d65f-7d7c-d64bff3454d4",
        "name": "Donut Delights",
        "vendor_slug": "216.1"
    },
    {
        "description": "Deep-fried butternut squash ravioli sprinkled with maple cinnamon sugar. Served with a side of whipped ricotta. (Vegetarian)",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/fried-butternut-squash-ravioli/landing.720x600.jpg",
        "slug": "fried-butternut-squash-ravioli",
        "id": "9831ef90-1417-c865-8460-096571b4fdb3",
        "name": "Fried Butternut Squash Ravioli",
        "vendor_slug": "2991.1"
    },
    {
        "description": "Two deep-fried locally grown green tomato slices in a crust of Whole Grain Milling Co. High Lysine Cornmeal, with mustard mayonnaise made with Lost Capital Economics Coarse Spicy Ale Mustard, and local lettuce on a toasted brioche bun from The Good Bread Company. BLT is served with bacon from Pastures a Plenty & Hidden Stream Farm. Vegetarian option is served with locally produced charred sweet corn relish.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/fried-green-tomato-sandwich-in-two-varieties/landing.720x600.jpg",
        "slug": "fried-green-tomato-sandwich-in-two-varieties",
        "id": "d5a8feb9-9c0f-66b0-814c-5cd5c48429c2",
        "name": "Fried Green Tomato Sandwich in Two Varieties \u2013 BLT and Vegetarian",
        "vendor_slug": "2878.1"
    },
    {
        "description": "A Betty and Earl\u2019s biscuit made with fruity cereal milk and cereal bits, drizzled with icing flavored with fruity cereal, and topped with more cereal bits.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/fruity-cereal-milk-biscuit/landing.720x600.jpg",
        "slug": "fruity-cereal-milk-biscuit",
        "id": "dbb1dcae-17d7-da74-02cd-170a5286cf2a",
        "name": "Fruity Cereal Milk Biscuit",
        "vendor_slug": "1416.1"
    },
    {
        "description": "Traditional Hmong-style steamed bun stuffed with ground pork, egg and spices \u2013 a recipe from Chef Yia Vang\u2019s mom. Served with choice of Krunchy Chili Oil, Kua Txob Hot Pepper Sauce or Lemongrass Scallion Dressing.",
        "image": "https://assets.mnstatefair.org/_core/img/database/new-this-year/food/galabao/landing.720x600.jpg",
        "slug": "galabao",
        "id": "a8ec4316-d746-b2ea-03fe-270e74ad5880",
