=== djnugent/cdn/schemas/pois.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "description": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "image": {
                "type": [
                    "string",
                    "null"
                ],
                "format": "uri"
            },
            "hours": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "cost": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "category": {
                "type": [
                    "string",
                    "null"
                ],
                "enum": [
                    "ride_attraction",
                    "stage",
                    "booth_showcase",
                    "guest_services",
                    "building",
                    null
                ]
            },
            "slug": {
                "type": "string"
            },
            "id": {
                "type": "string",
                "format": "uuid"
            },
            "name": {
                "type": "string"
            },
            "location": {
                "type": "object",
                "properties": {
                    "image": {
                        "type": [
                            "string",
                            "null"
                        ],
                        "format": "uri"
                    },
                    "directions": {
                        "type": [
                            "string",
                            "null"
                        ]
                    },
                    "lat": {
                        "type": "number",
                        "format": "float"
                    },
                    "lng": {
                        "type": "number",
                        "format": "float"
                    }
                },
                "required": [
                    "image",
                    "lat",
                    "lng"
                ]
            }
        },
        "required": [
            "description",
            "image",
            "hours",
            "cost",
            "category",
            "slug",
            "id",
            "name",
            "location"
        ]
    }
}

=== djnugent/cdn/pois.json
[
  {
    "description": "Thousands of talented 4-H youth from throughout the state showcase their award-winning exhibits on topics from aerospace to fine arts to health to veterinary science and dozens of categories in between. High-energy song and dance performances, engineering challenges, and a wide range of demonstrations also fill the building.\n\nFor information on all 4-H activities at the fair, download the 4-H at the Minnesota State Fair app or visit https://extension.umn.edu/fairs-events-and-training/4-h-minnesota-state-fair",
    "image": "https://assets.mnstatefair.org/_core/img/database/locations/4h-building/featured.848x477.jpg?v=20210629.224419",
    "hours": "9:00\u00a0am \u2013 9:00\u00a0pm; Closes at 8 p.m. on Labor Day",
    "cost": null,
    "category": "building",
    "slug": "4h-building",
    "id": "7b3f2c07-b4ba-117c-350b-20840f39a121",
    "name": "4-H Building",
    "location": {
      "image": "https://assets.mnstatefair.org/_core/img/database/locations/4h-building/featured.848x477.jpg?v=20210629.224419",
      "directions": null,
      "lat": 44.983305,
      "lng": -93.167568
    }
  },
  {
    "description": "Home to the most extreme thrill rides and attractions at the Minnesota State Fair!\n\nRock Climbing Wall:\n\u2022 $7 per person\n\nSkyscraper:\n\u2022 $40 per rider ($30 during Early Bird Special hours)\n\nSling Shot:\n\u2022 $40 per rider ($30 during Early Bird Special hours)\n\nTurbo Bungy:\n\u2022 $7 per rider",
    "image": "https://assets.mnstatefair.org/_core/img/database/locations/adventure-park/featured.848x477.jpg?v=20210629.224420",
    "hours": "9:00\u00a0am \u2013 11:00\u00a0pm; Closes at 9 p.m. on Labor Day. Daily closing times for Adventure Park may vary. Ticket booth close \u00bd hour before rides & games close.",
    "cost": "See each individual attraction for pricing.\n\nNotes: Adventure Park attractions do not accept Mighty Midway and Kidway tickets.\n\n",
    "category": "ride_attraction",
    "slug": "adventure-park",
    "id": "519f91ce-ccd6-00f8-0d3e-4513b976e631",
    "name": "Adventure Park",
    "location": {
      "image": "https://assets.mnstatefair.org/_core/img/database/locations/adventure-park/featured.848x477.jpg?v=20210629.224420",
      "directions": null,
      "lat": 44.97814,
      "lng": -93.171746
    }
  },
  {
    "description": "Farm hands ages 11+ can grab a bookmark and pencil to learn even more about the farm and agriculture! At each stop along the path, answer agriculture-related trivia, and at the end of your journey, check your answers at the Ag-Vestigator Education Station. Receive a ribbon for your farm knowledge! Located within Little Farm Hands.",
    "image": null,
    "hours": "8:00\u00a0am \u2013 7:00\u00a0pm",
    "cost": null,
    "category": "booth_showcase",
    "slug": "ag-vestigator-activitiy",
    "id": "8e081b5e-d4a4-9482-926e-68896849562a",
    "name": "Ag-Vestigator Education Station",
    "location": {
      "image": null,
      "directions": null,
      "lat": 44.985493,
      "lng": -93.169785
    }
  },
  {
    "description": "Minnesota\u2019s bounty abounds in this iconic octagon-shaped building, which hosts the fair\u2019s popular crop art competition featuring art created using Minnesota-grown seeds; the Minnesota Craft Brewers Guild, which sells flights of Minnesota-made craft beer; ribbon-winning fruits and vegetables, including giant pumpkins and the Minnesota apple exhibit; gorgeous flower shows; bee & honey displays; a towering center rotunda with an annually themed exhibit by local florists; and more.",
    "image": "https://assets.mnstatefair.org/_core/img/database/locations/agriculture-horticulture-building/featured.848x477.jpg?v=20210629.224419",
    "hours": "9:00\u00a0am \u2013 9:00\u00a0pm; Closes at 8 p.m. on Labor Day",
    "cost": null,
    "category": "booth_showcase",
    "slug": "agriculture-horticulture-building",
    "id": "c73735f6-6eae-be29-7efe-81743b8ad0dd",
    "name": "Agriculture Horticulture Building",
    "location": {
      "image": "https://assets.mnstatefair.org/_core/img/database/locations/agriculture-horticulture-building/featured.848x477.jpg?v=20210629.224419",
      "directions": null,
      "lat": 44.979215,
      "lng": -93.169699
    }
  },
  {
    "description": "The Aisle of Breeds, presented by the Minnesota Horse Expo and the Minnesota Horse Council, showcases different breeds and types of horses throughout the 12 days of the State Fair. Be sure to stop by to meet the horses and their owners, get answers to your equine questions, pet a horse or two and find out where to take horseback riding lessons in Minnesota or go for a trail ride.",
    "image": "https://assets.mnstatefair.org/_core/img/database/locations/aisle-of-breeds/featured.848x477.jpg?v=20210629.224423",
    "hours": "Please check the daily schedule for detailed Horse Barn hours.",
    "cost": null,
    "category": "booth_showcase",
    "slug": "aisle-of-breeds",
    "id": "7cabaeb2-2d8f-8a1e-5ffa-222a60e0c01c",
    "name": "Aisle of Breeds",
    "location": {
      "image": "https://assets.mnstatefair.org/_core/img/database/locations/aisle-of-breeds/featured.848x477.jpg?v=20210629.224423",
      "directions": null,
      "lat": 44.979194,
      "lng": -93.176192
    }
  },
  {
    "description": "Step inside the Alphabet Forest and discover alphabet activities for all ages. Take pictures with Fair Letters, create alphabet Ferris wheels, add your fair words to the Fair Dictionary, pause for a break with a good children\u2019s book (including several in Braille) and more! Guests can meet a different author or illustrator each day in the Alphabet Forest at the Blue Ribbon Homegrown Author Showcase. Activities provided by Debra Frasier, Winding Oak and the Minnesota State Fair and supported by the Minnesota State Fair Foundation.\n\nDuring your visit to the fair, play the Fabulous Fair Alphabet Game. Print a Fabulous Fair Alphabet game card or pick one up from any State Fair Information Booth. Look for words in what you SEE, HEAR, READ, FEEL - and certainly in what you EAT - at the fair! Write these words on the card, recording two words for each letter of the alphabet. (For example: Write a word that begins with \u201cA\u201d beside the printed A. Remember that X\u2019s are rare - simply look for words that contain an X.) Bring your completed card to the Alphabet Forest at Baldwin Park and win a blue ribbon!",
    "image": "https://assets.mnstatefair.org/_core/img/database/locations/alphabet-forest/featured.848x477.jpg?v=20210629.224419",
    "hours": "9:00\u00a0am \u2013 8:00\u00a0pm",
    "cost": null,
    "category": "booth_showcase",
    "slug": "alphabet-forest",
    "id": "4fdfa933-7455-53d0-6194-bcf3afcb6bf2",
    "name": "Alphabet Forest",
    "location": {
      "image": "https://assets.mnstatefair.org/_core/img/database/locations/alphabet-forest/featured.848x477.jpg?v=20210629.224419",
      "directions": null,
      "lat": 44.983409,
      "lng": -93.16863
    }
  },
  {
    "description": "This educational exhibit for the whole family features sheep displays and fun, hands-on activities. The Baa Booth is open the first eight days of the fair.",
    "image": "https://assets.mnstatefair.org/_core/img/database/locations/baa-booth/featured.848x477.jpg?v=20210629.224426",
    "hours": "Please check the daily schedule for detailed Sheep & Poulty Barn hours.",
    "cost": null,
    "category": "booth_showcase",
    "slug": "baa-booth",
    "id": "7c585552-9ad1-c1a2-9496-f4cd4380a211",
    "name": "Baa Booth",
    "location": {
      "image": "https://assets.mnstatefair.org/_core/img/database/locations/baa-booth/featured.848x477.jpg?v=20210629.224426",
      "directions": null,
      "lat": 44.979008,
      "lng": -93.174468
    }
  },
  {
    "description": "Entertainers are booked and compensated by the independent concessionaires that host them at these privately owned venues. The Minnesota State Fair is not responsible for scheduling of any entertainers listed below (schedules are posted as information becomes available and are subject to change).",
    "image": null,
    "hours": null,
    "cost": null,
    "category": "stage",
    "slug": "bob-fm",
    "id": "aaa26890-b27c-5dbe-d4e5-e7af14a32a00",
    "name": "BOB FM",
    "location": {
      "image": null,
      "directions": null,
      "lat": 44.97871,
      "lng": -93.174409
    }
  },
  {
    "description": "Immerse yourself in the wonders of butterflies! These stunning creatures flit and soar around \u2013 all before your eyes!",
    "image": "https://assets.mnstatefair.org/_core/img/database/locations/butterfly-house/featured.848x477.jpg?v=20210629.224423",
    "hours": "9:00\u00a0am \u2013 10:00\u00a0pm; Closes at 9 p.m. on Labor Day",
    "cost": "$4 per person\n\nNotes: This attraction does not accept Mighty Midway and Kidway ride & game tickets. Accepts credit cards.\n\n",
    "category": "ride_attraction",
    "slug": "butterfly-house",
    "id": "c1adb0f4-ff18-8fcc-e47e-b2e2cdc69e55",
    "name": "Butterfly House",
    "location": {
      "image": "https://assets.mnstatefair.org/_core/img/database/locations/butterfly-house/featured.848x477.jpg?v=20210629.224423",
      "directions": null,
      "lat": 44.981437,
      "lng": -93.170792
    }
  },
  {
    "description": "Entertainers are booked and compensated by the independent concessionaires that host them at these privately owned venues. The Minnesota State Fair is not responsible for scheduling of any entertainers listed below (schedules are posted as information becomes available and are subject to change).",
    "image": null,
    "hours": null,
    "cost": null,
    "category": "stage",
    "slug": "cafe-caribe",
    "id": "8ddf66be-3be9-9541-65cf-d1bd82fdd829",
    "name": "Cafe Caribe",
    "location": {
      "image": null,
      "directions": null,
      "lat": 44.979693,
      "lng": -93.173768
    }
  },
  {
    "description": null,
    "image": null,
